config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :galleries do
  	member do
  		post :update_name
  	end
    collection do
      post :import_csv
      get :images_count
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {:registrations => "registrations"}

  root to: 'home#about_us'

  get  'home/about_us'
  get  'home/contact_us'
  post 'home/contact_form'

  namespace :api, defaults: {format: 'json'} do
    post 'create_user'    => 'home#create_user'
    post 'create_gallery' => 'home#create_gallery'
    post 'contact_form'   => 'home#contact_form'
    get  'gallery/:id'    => 'home#get_gallery'
    match '*url', :to => 'home#no_route', via: [:get, :post]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  mount_uploader :image, ImageUploader
  paginates_per 5

  validates :name, presence: true, uniqueness: true
  validates :image, presence: true

  def self.import(file)
    if CSV.foreach(file.path).count == 0 || CSV.foreach(file.path, headers: true).count == 0
      return "No data found"
    else
      valid_rows = 0
      invalid_rows = 0

    	CSV.foreach(file.path, headers: true) do |row|
        name = row.to_hash["name"]
        image = row.to_hash["image"]

        if name.blank? || image.blank?
          invalid_rows += 1
        else
          valid_rows += 1
          Gallery.create(name: name, remote_image_url: image)
        end
    	end
      return "Data Imported. Valid Rows: #{valid_rows} Invalid Rows: #{invalid_rows}"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  def send_devise_notification(notification, token, opts)
    DeviseConfirmWorker.perform_async(notification, self.email, token, self.password, opts)
  end
end

app/controllers/api/home_controller.rb
class Api::HomeController < ApplicationController
  protect_from_forgery with: :null_session

  def create_user
    user = User.new(user_params)
    if user.save
      render json: {code: 200, status: "Success", message: "User created Successfully"}
    else
      render json: {code: 500, status: "Failure", message: user.errors.messages}
    end
  end

  def create_gallery
    gallery = Gallery.new(gallery_params)
    if gallery.save
      render json: {code: 200, status: "Success", message: "Gallery created Successfully"}
    else
      render json: {code: 500, status: "Failure", message: gallery.errors.messages}
    end
  end

  def contact_form
    begin
      UserMailer.acknowledgement_user(params).deliver_now()
      render json: {code: 200, status: "Success", message: "Contact form submitted."}
    rescue Exception => e
      render json: {code: 500, status: "Failure", message: e.message}
    end
  end

  def get_gallery
    gallery = Gallery.where(id: params[:id]).first
    if gallery.blank?
      render json: {code: 500, status: "Failure", message: "No Gallery Found."}
    else
      render json: {code: 200, status: "Success", message: "Successful", data: gallery}
    end
  end

  def no_route
    render json: {code: 500, status: "Failure", message: "No route matches"}
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def gallery_params
    params.require(:gallery).permit(:name, :remote_image_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_gallery, only: [:edit, :update, :show, :destroy, :update_name]

  def index
    @galleries = Gallery.order("created_at DESC").page params[:page]
  end

  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new(gallery_params)
    if @gallery.save
      redirect_to galleries_path, notice: "Gallery created successfully."
    else
      render :new
    end
  end

  def show
    
  end

  def edit
    
  end

  def update
    if @gallery.update(gallery_params)
      redirect_to galleries_path, notice: "Gallery updated successfully."
    else
      render :edits
    end
  end

  def destroy
    @gallery.destroy
    redirect_to galleries_path, notice: "Gallery deleted successfully."
  end

  def update_name
  	if @gallery.update_attributes(name: params[:name])
  		render json: {status: true, message: "Name updated successfully.", color: "green"}
  	else
  		render json: {status: false, message: @gallery.errors.messages.to_s, color: "red"}
  	end
  end

  def import_csv
    if params[:file].blank?
      redirect_to galleries_path, alert: "No File to import"
    else
      data = Gallery.import(params[:file])
      redirect_to galleries_path, notice: data
    end
  end

  def images_count
    render json: {status: true, count: Gallery.all.count}
  end

  private

  def set_gallery
    @gallery = Gallery.find(params[:id])
  end

  def gallery_params
    params.require(:gallery).permit(:name,:image)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def contact_form
    ContactUsWorker.perform_async(params[:name], params[:email])
    redirect_to root_url, notice: "We will contact you soon."
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def create
    random_password = (('a'..'z').to_a.shuffle[0,2]+(0..9).to_a.shuffle[0,7]+('A'..'Z').to_a.shuffle[0,1]).join
    params[:user][:password] = random_password
    params[:user][:password_confirmation] = random_password
    super
  end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:div, msg) }.join

    html = <<-HTML
    <div id="error_explanation">
      #{messages}
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/galleries_helper.rb
module GalleriesHelper
	def get_galler_image(gallery)
		image_tag(gallery.image.url(:thumb)) unless gallery.image.url.nil?
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/galleries/_form.html.erb
<%= form_for @gallery do |form| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @gallery.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :gallery_name, required: "true", gallery_id: params[:id] %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :gallery_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing Gallery</h1>

<%= render 'form', gallery: @gallery %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<center><div class="images_count">Images Count:<span id="count"></span></div></center>
<div class="gallery_page">
  <h1>Galleries</h1>

  <%= link_to 'New Gallery', new_gallery_path, class: "new_btn btn btn-primary pull-right" %>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Image</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% cache(@galleries, expires_in: 5.minute) do %>
        <% @galleries.each do |gallery| %>
          <tr>
            <td><%= gallery.name %></td>
            <td><%= get_galler_image(gallery) %></td>
            <td><%= link_to 'Show', gallery %></td>
            <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
            <td><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<%= paginate @galleries %>

<hr>

<h3>Import CSV</h3>
<%= form_tag import_csv_galleries_path, :multipart => true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import CSV" %>
<% end %>

<% content_for :custom_js do %>
  <script type="text/javascript">
    setInterval(fetch_images_count, 5000);
  </script>
<% end %>

app/views/galleries/new.html.erb
<h1>New Gallery</h1>

<%= render 'form', gallery: @gallery %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @gallery.name %>
</p>

<p>
  <strong>Image:</strong><br>
  <%= get_galler_image(@gallery) %>
</p>

<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %>

app/views/home/about_us.html.erb
<div class="container about_us_page">
  <img src="https://www.maropost.com/wp-content/uploads/2016/10/m-landing-sun-hero-large-copy.png" alt="maropost" />
  <div class="jumbotron">
    <h2>We Are Maropost</h2>
    <h4>We make the world's best marketing and sales platforms</h4>
    <div class="panel">
      <h5>Maropost is the leading global provider of on-demand marketing, sales, commerce, and infrastructure solutions. We offer the world’s best marketing and sales cloud platforms combined with industry leading customer support and client success.</h5>
      <a href="https://www.maropost.com/leadership-team/">MEET OUR LEADERSHIP TEAM</a>
    </div>
    <div class="panel">
      <h5>Maropost was founded in 2011 by CEO and Chairman Ross Andrew Paquette. We are headquartered in Toronto, Canada, with offices in New York, USA, London, U.K., and Chandigarh, India.</h5>
      <a href="https://www.maropost.com/client-case-studies/">READ OUR CASE STUDIES</a>
    </div>
    <div class="panel">
      <h5>Maropost is the fastest growing company in Toronto and among the fastest growing companies in North America. In 2016, Maropost was ranked 4th in Deloitte's Canadian Technology Fast 50, 7th in the annual PROFIT 500 of Canada's fastest- growing companies, and 37th in the North America-wide Deloitte Fast 500.</h5>
      <a href="http://www.maropost.com/careers-at-maropost/">CHECK OUT OUR CAREERS</a>
    </div>
  </div>
</div>

app/views/home/contact_us.html.erb
<h3>Contact Us</h3>

<iframe class="map" frameborder="0" src="https://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=maropost&output=embed"></iframe>

<hr>

<h4>TELL US ABOUT YOURSELF, AND WE'LL GET BACK TO YOU RIGHT AWAY </h4>

<div class="container">
  <%= form_tag home_contact_form_path do %>

    <div class="field">
      <label>Name</label>
      <input type="text" name="name" required="true">
    </div>

    <div class="field">
      <label>Email</label>
      <input type="email" name="email" required="true">
    </div>

    <div class="field">
      <label>Mobile</label>
      <input type="number" name="mobile">
    </div>

    <div class="field">
      <label>Description</label>
      <textarea rows="3" name="desc"></textarea>
    </div>

    <div class="actions">
      <input type="submit">
    </div>

  <% end %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_flash_messages.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default navbar-bottom">
  <center>
    <p class="text-muted">© 2017 Maropost Inc. All rights reserved. | <a href="/home/contact_us">Contact Us</a></p>
  </center>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Demo</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'About Us', home_about_us_path %></li>
        <li><%= link_to 'Contact Us', home_contact_us_path %></li>
        <li><%= link_to 'Gallery', galleries_path %></li>
      </ul>

      <div class="pull-right">
        <h5>
          <% if user_signed_in? %>
            <%= link_to 'Change Password', edit_user_registration_path %>
            Logged in as <strong><%= current_user.email %></strong>
            <%= link_to "Logout", destroy_user_session_path %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path %> |
            <%= link_to "Login", new_user_session_path %>
          <% end %>
        </h5>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render partial: "layouts/header" %>
    <div class="container main_container">
      <%= render partial: "layouts/flash_messages" %>
      
      <%= yield %>
    </div>
    <%= render partial: "layouts/footer" %>

   <script type='text/javascript'>
      setTimeout("$('.alert').slideUp();", 6000);
   </script>

   <%= yield :custom_js %>

  </body>
</html>